vars: {
  d2-config: {
    layout-engine: dagre
  }
}

Log.h
Log.cpp -> Log.h
Log.cpp -> utils.FileSystemUtil.h
Log.cpp -> utils.Platform.h
Log.cpp -> Settings.h
Log.cpp -> Paths.h

Settings.h
Settings.cpp -> Settings.h
Settings.cpp -> utils.FileSystemUtil.h
Settings.cpp -> Log.h
Settings.cpp -> Scripting.h
Settings.cpp -> utils.Platform.h
Settings.cpp -> utils.StringUtil.h
Settings.cpp -> Paths.h
Settings.h -> utils.Delegate.h

Paths.h
Paths.cpp -> Paths.h
Paths.cpp -> utils.FileSystemUtil.h
Paths.cpp -> utils.StringUtil.h

Scripting.h
Scripting.cpp -> Scripting.h
Scripting.cpp -> Log.h
Scripting.cpp -> Paths.h
Scripting.cpp -> utils.Platform.h
Scripting.cpp -> utils.FileSystemUtil.h
Scripting.cpp -> utils.StringUtil.h
Scripting.cpp -> utils.VectorEx.h

utils {
  Delegate.h
  FileSystemUtil.h
  Platform.h
  StringUtil.h
}
